name: PR Commit with Ubucode Details

on:
  pull_request:
    branches: 
      - main
      - dev

jobs:
  commit-with-user1-details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config user.name "ubucode"
          git config user.email "hi@ubucode.co.za"


      - name: Create Commit as ubucode
        run: |
            git checkout ${{ github.head_ref }}
            git commit --allow-empty -m "Verified PR by User2"

      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Merge the PR using GitHub CLI
          gh pr merge ${{ github.event.pull_request.number }} --merge